### PR TITLE
meh.. forgot to test.

### PR DESCRIPTION
**Pull request by f34rdotcom**

### CODE REVIEW

**Comment by digiblur** [comment]
Looks like the latest update to things got my Pi stuck in a loop somewhere.  I can see a process stuck in 100% cpu and the web interface shows.:  Services might still be starting - please wait and try again. If this continues, please let us know on GitHub. You can also email us at Support.

I should have a image of the SD card I'll restore.

**Comment by digiblur** [comment]
Sure, only thing I've done so far is this:

 $ docker ps
# shows the <container ID> of alarmdecoder

$ docker exec -it <container ID> bash
# we are now in the container's file system

$ python manage.py initdb
# this re-initializes the database

$ exit
# we are out of the container

$ docker restart <container ID>
# wait 1-2 minutes

**Comment by digiblur** [comment]
Thanks for the help with getting this going and glad I could help out with a different test scenario.  As requested here is the command we ran inside the container after the investigation of things:

sudo python setup.py install

**Comment by weevis** [comment]
The webapp will update the library as long as the library is installed from
source (git)

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by digiblur** [comment]
I do remember the /update/ HTML page having two updates ready.  I don't remember what order I clicked the update buttons in though.

**Pull request merged**
